### ISSUE TITLE
Fehlermeldung "The Actor does not exist in actors" nach dem Erfolgreichen Vorbereiten

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsa5_introduction#6]
FVTT 11.306
DSA 5.0.8

Nach dem Erfolgreichen Vorbereiten des Moduls "Einführungsabenteuer" erscheint mehrfach die Fehlermeldung "The Actor does not exist in actors" (Fehler Konsole siehe Screenshot 1)

Komischerweise wird Arbosch nicht inden richtigen Ordner gelegt (siehe Screenshot 2)

![image](https://github.com/Plushtoast/dsa5_introduction/assets/78543670/1c78948b-fa07-45b1-a3c4-7b6f9ad4b9a1)
![image](https://github.com/Plushtoast/dsa5_introduction/assets/78543670/64a2fdee-f124-414d-9322-b4970d789009)

**Comment by Plushtoast** [comment]
Die Fehlermeldung kann ich nicht wegmachen. Sie hat aber auch keine Auswirkungen
